version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    # image: jeetdockerize/productmanagement-client
    ports:
      - "4173:4173"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    # image: jeetdockerize/productmanagement-server
    ports:
      - "8001:8000"
    env_file:
      - ./server/.env
    depends_on:
      mysql:
        condition: service_healthy # Ensure MySQL is ready
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    env_file:
      - ./.env
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge